name: Push-to-Local-Ubuntu

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Local Ubuntu on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Install Apache and Deploy Files
        run: |
          # Make sure to replace with your local machine's IP and username
          ssh mitrah095@172.26.91.24 << 'EOF'
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            cd /home/mitrah095  # Replace with the correct path
            sudo mv * /var/www/html
          EOF
